apiVersion: v1
kind: Service
metadata:
  name: fa
  labels:
    app: fa
spec:
  clusterIP: None
  selector:
    app: fa
  ports:
    - name: fa
      port: 80 #Service port
      targetPort: 80 #container port
    - name: sftp
      port: 22
      targetPort: 22
  # type: LoadBalancer
  type: ClusterIP
