repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# -   repo: https://github.com/golangci/golangci-lint
#     rev: v1.47.2
#     hooks:
#     -   id: golangci-lint

-   repo: local
    hooks:
    - id: golangci-lint
    name: golangci-lint
    description: Fast linters runner for Go.
    entry: make lint
    types: [go]
    language: system
    pass_filenames: false
