package logger

const (
	// TenantID ...
	TenantID = "tenant_id"
	// UserID ...
	UserID = "user_id"
	// Username ...
	Username = "username"
	// Module ...
	Module = "module"
	// Path ...
	Path = "path"
	// BackupID ...
	BackupID = "backup_id"
	// RestoreID ...
	RestoreID = "restore_id"
)
